ECommercePrototype/ECommercePrototype.Web/Models/Authentication/IdentityHelper.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ECommercePrototype.Web.Models.Authentication
{
    public class IdentityHelper
    {
        public IdentityHelper()
        {

        }
        [Required]
        [DataType(DataType.EmailAddress)]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name ="Confirm Password")]
        public string ConfirmPassword { get; set; }
    }
}

ECommercePrototype/ECommercePrototype.Web/Controllers/AuthenticationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using ECommercePrototype.Web.Models.Authentication;
using ECommercePrototype.Web.Models.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace ECommercePrototype.Web.Controllers
{
    public class AuthenticationController : Controller
    {
        readonly IAuthenticateAPI _authenticateAPI;

        public AuthenticationController(IAuthenticateAPI authenticateAPI)
        {
            _authenticateAPI = authenticateAPI;
        }
        // GET: Authentication
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Register(string email, string password)
        {
                IdentityHelper identity = new IdentityHelper
                {
                    Email = email,
                    Password = password,
                    ConfirmPassword = password
                };
                string url = "api/authenticate";

                HttpClient client = _authenticateAPI.CreateClient();

                var item = new StringContent(JsonConvert.SerializeObject(identity), Encoding.UTF8, "application/json");

                HttpResponseMessage response = client.PostAsync(url, item).Result;
            if(response.IsSuccessStatusCode)
            {
                return View("Index", "Catalogue");
            }
            return View();
        }

        //// GET: Authentication/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}

        //// POST: Authentication/Create
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create(IFormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add insert logic here

        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
    }
}

ECommercePrototype/ECommercePrototype.Web/Views/Authentication/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4>Please Enter your Registration Details</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Register" asp-controller="Authentication" method="post">
            <div>
                <label for="email">Enter Email Address</label>
                <input type="text" id="email" placeholder="Enter Email here" name="email" />
            </div>
            <div>
                <label for="password">Enter Password</label>
                <input type="text" id="password" placeholder="Enter Password here" name="password" />
            </div>
            <div>
                <input type="submit" />
            </div>
            @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div>
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ConfirmPassword" class="control-label"></label>
                <input asp-for="ConfirmPassword" class="form-control" />
                <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default"/>
            </div>*@
        </form>
    </div>
</div>

<div>
    <a asp-controller="Catalogue" asp-action="Index">Back to Home</a>
</div>
@section Scripts{ 
    <partial name="_ValidationScriptsPartial" />
}