ECommercePrototype/ECommercePrototype.Web/Models/Catalogue/CatalogueHelper.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ECommercePrototype.Web.Models.Catalogue
{
    public class CatalogueHelper
    {
        public CatalogueHelper()
        {

        }
        public int ItemID { get; set; }
        public string ItemName { get; set; }
        public string ItemDescription { get; set; }
        public decimal ItemPrice { get; set; }
        public int ItemAvailableStock { get; set; }
        public string ItemBrand { get; set; }
        public string ItemType { get; set; }
        public string Pic { get; set; }
        public string SelectedQuantity { get; set; }
        public List<SelectListItem> QuantitySelectable { get; set; }

        public void GetQuantity()
        {
            QuantitySelectable = new List<SelectListItem>();
            for (int i = 1; i <= ItemAvailableStock; i++)
            {
                var item = new SelectListItem { Text = i.ToString() };
                QuantitySelectable.Add(item);
            }
        }
    }
}

ECommercePrototype/ECommercePrototype.Web/Models/Catalogue/CatalogueItemRepository.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ECommercePrototype.Web.Models.Catalogue
{
    public class CatalogueItemRepository
    {
        public List<CatalogueHelper> catalogue { get; set; }
        public SelectList catalogueBrands;
        public SelectList catalogueTypes;

        public string catalogueBrand { get; set; }
        public string catalogueType { get; set; }
    }
}

ECommercePrototype/ECommercePrototype.Web/Controllers/CatalogueController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net.Http;
using System.Text;
using ECommercePrototype.Web.Models;
using System.Net.Http.Headers;
using System.Net;
using ECommercePrototype.Web.Models.Interfaces;
using ECommercePrototype.Web.Models.Catalogue;
using Microsoft.AspNetCore.Mvc.Rendering;
using ECommercePrototype.Web.Models.APIConnections;

namespace ECommercePrototype.WebFrontEnd.Controllers
{
    public class CatalogueController : Controller
    {
        readonly ICatalogueAPI _catalogueAPI;

        public CatalogueController(ICatalogueAPI catalogueAPI)
        {
            _catalogueAPI = catalogueAPI;
        }

        // GET: Catalogue
        public async Task<IActionResult> Index(string catalogueBrand, string searchString, string catalogueType)
        {
            string url = "api/catalogue";
            CatalogueItemRepository ItemRepo = new CatalogueItemRepository();

            HttpClient client = _catalogueAPI.CreateClient();

            HttpResponseMessage response = await client.GetAsync(url);

            // checking the response is successful or not which is sent using HttpClient
            if (response.IsSuccessStatusCode)
            {
                var result = response.Content.ReadAsStringAsync().Result;

                ItemRepo.catalogue = JsonConvert.DeserializeObject<List<CatalogueHelper>>(result);
            }

            var brands = from m in ItemRepo.catalogue
                         select m.ItemBrand;

            var searchItem = from m in ItemRepo.catalogue
                             select m;

            var types = from m in ItemRepo.catalogue
                         select m.ItemType;

            if (!string.IsNullOrEmpty(searchString))
            {
                searchItem = searchItem.Where(s => s.ItemName.Contains(searchString));
            }

            if (!string.IsNullOrEmpty(catalogueBrand))
            {
                searchItem = searchItem.Where(x => x.ItemBrand.Contains(catalogueBrand));
            }

            if (!string.IsNullOrEmpty(catalogueType))
            {
                searchItem = searchItem.Where(x => x.ItemType.Contains(catalogueType));
            }

            ItemRepo.catalogueBrands = new SelectList(brands.Distinct().ToList());
            ItemRepo.catalogueTypes = new SelectList(types.Distinct().ToList());

            ItemRepo.catalogue = searchItem.ToList();

            return View(ItemRepo);
        }

        // GET: CatalogueItem by ID
        public async Task<IActionResult> Details(int? id)
        {
            string url = $"api/catalogue/{id}";
            CatalogueHelper catalogueItem = new CatalogueHelper();

            HttpClient client = _catalogueAPI.CreateClient();

            HttpResponseMessage response = await client.GetAsync(url);

            if (response.IsSuccessStatusCode)
            {
                catalogueItem = response.Content.ReadAsAsync<CatalogueHelper>().Result;
            }

            ViewBag.CatalogueItemPic = "~/images/" + catalogueItem.Pic;

            catalogueItem.GetQuantity();

            return View(catalogueItem);
        }

    }

}

ECommercePrototype/ECommercePrototype.Web/Views/Catalogue/Details.cshtml
@model ECommercePrototype.Web.Models.Catalogue.CatalogueHelper

@{
    ViewData["Title"] = "Catalogue Item Details";
}

<h2>Details</h2>
<div>
    <h4>Catalogue Item Description</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ItemID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ItemID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ItemName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ItemName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ItemDescription)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ItemDescription)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ItemPrice)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ItemPrice)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ItemAvailableStock)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ItemAvailableStock)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ItemBrand)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ItemBrand)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ItemType)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ItemType)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Pic)
        </dt>
        <dd>
            <img src="@Url.Content(ViewBag.CatalogueItemPic)" width="42" height="42" />
        </dd>
    </dl>
</div>
<div>
    <p class="btn">
        @Html.ActionLink("Add Item To Basket", "AddItemToBasket", "Basket", Model)
    </p>
    <a asp-action="Index">Back to Shopping</a>
</div>

ECommercePrototype/ECommercePrototype.Web/Views/Catalogue/Index.cshtml
@model ECommercePrototype.Web.Models.Catalogue.CatalogueItemRepository
@{
    ViewData["Title"] = "Home page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div id="header" class="header">
    <h1>Welcome</h1>
    <h2>E-Comm can help you find what you are looking for</h2>
</div>

<p>Search By Name</p>
<form asp-controller="Catalogue" asp-action="Index">
    <p>
        <input type="text" name="SearchString">
        <input type="submit" value="Filter" />
    </p>
</form>

@section sidebar
    {
    <ul id="sidebar">
        <li>
            <p>Search By Brand</p>
            <form asp-controller="Catalogue" asp-action="Index">
                <p>
                    <select asp-for="catalogueBrand" asp-items="Model.catalogueBrands">
                        <option value="">All</option>
                    </select>
                    <input type="submit" value="Filter" />
                </p>
            </form>
        </li>
        <li>
            <p>Search By Type</p>
            <form asp-controller="Catalogue" asp-action="Index">
                <p>
                    <select asp-for="catalogueType" asp-items="Model.catalogueTypes">
                        <option value="">All</option>
                    </select>
                    <input type="submit" value="Filter" />
                </p>
            </form>
        </li>
        @*<li>
                <p>Search By Name</p>
                <form asp-controller="Catalogue" asp-action="Index">
                    <p>
                        <input type="text" name="SearchString">
                        <input type="submit" value="Filter" />
                    </p>
                </form>
            </li>*@
    </ul>
}
<p class="lead">Each item listed has detailed information to help you choose the right product</p>

@if (Model.catalogue != null)
{
    <table class="table" cellpadding="1" cellspacing="1" border="1">
        <thead>
            <tr>
                <th>
                    Item Number
                </th>
                <th>
                    Name
                </th>
                <th>
                    Picture
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.catalogue)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ItemID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ItemName)
                    </td>
                    <td>
                        <img src="~/images/@item.Pic" width="42" height="42" />
                    </td>
                    <td>
                        @Html.ActionLink("View Item Details", "Details", new { id = item.ItemID })
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <h1>There is an issue with the Catalogue</h1>
}